-- ADD COURSES IN MIMO APP

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory", 
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('HTML', 
'html', 
'Start building web pages using the foundational markup language of the web', 
'Learn the essentials of HTML to build websites', 
'build', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947398/asjvuxdjywqefqny8e15.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('CSS', 
'css', 
'Style your web pages using CSS, the language designed to bring HTML pages to life', 
'Learn the essentials of CSS to style websites', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947722/h5pbit2dly8ogyztbwqo.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('JavaScript', 
'javascript', 
'Create dynamic web pages with the world''s most used programming language', 
'Learn the essentials of JavaScript to make websites interactive', 
'build', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711948132/qkutp3ydt4qgifkhrtit.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('SQL', 
'sql', 
'Get to know databases, tables, and queries while learning smart ways to extract and manage data', 
'Learn how to use SQL queries to extract and manage data', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711857335/zo9squricxx6vxot1npo.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('Python', 
'python', 
'Learn the essentials of the fun, all-purpose language Python', 
'Learn the essentials of the fun, all-purpose language Python', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711857873/woayw3xg6odhsbcynmsq.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('Swift', 
'swift', 
'Master Apple''s programming language and unlock the potential to create your own iOS apps', 
'Learn Apple''s programming language Swift', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711858135/dt3uu8jj8v3o5yskm0fw.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('Python Developer', 
'python-developer', 
'Become a Python developer: Learn the all-purpose language Python and build sophisticated programs', 
'Learn the all-purpose language Python to kickstart your development career', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711857873/woayw3xg6odhsbcynmsq.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('Front-End Developer', 
'front-end-developer', 
'Unlock Web Development: Dive Deep into HTML, CSS, and JavaScript, and conquer React', 
'Learn HTML, CSS, and JavaScript, and conquer React', 
'none', 
true, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947398/asjvuxdjywqefqny8e15.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947722/h5pbit2dly8ogyztbwqo.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711948132/qkutp3ydt4qgifkhrtit.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711950081/p6cgnfpyugvzwtlsjp2i.png');

INSERT INTO public.courses(title, 
slug, 
"descriptionContent", 
"shortDescriptionContent", 
"onboardCategory",
"isNew", 
"isHidden", 
"iconBanner")
VALUES ('Full-Stack Developer', 
'full-stack-developer', 
'Become a full-stack developer: Learn HTML, CSS, JavaScript, and React as well as NodeJS, Express, and SQL', 
'Learn HTML, CSS, JavaScript, and React as well as NodeJS, Express, and SQL', 
'build', 
false, 
false, 
'https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947398/asjvuxdjywqefqny8e15.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711947722/h5pbit2dly8ogyztbwqo.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711948132/qkutp3ydt4qgifkhrtit.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711950081/p6cgnfpyugvzwtlsjp2i.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711857335/zo9squricxx6vxot1npo.png https://res.cloudinary.com/dw3pxcshp/image/upload/v1711949071/shjkueoqkzrfxeboeanq.png');